version: "3.9"

services:
  frontend:
    build: ./frontend/url-shortener
    container_name: url_shortener_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

  api: 
    build: .
    container_name: url_shortener_api
    ports: 
      - "5000:5000"
    depends_on: 
      db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: url_shortener_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=121425
      - POSTGRES_DB=URLShorter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d URLShorter"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
